apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: cluster-simple-auth
  namespace: trailblazers
spec:
  entityOperator:
    topicOperator:
      reconciliationIntervalSeconds: 90
    userOperator:
      reconciliationIntervalSeconds: 120
  cruiseControl: {}
  kafka:
    version: 3.3.1
    config:
      offsets.topic.replication.factor: 2
      default.replication.factor: 2
      min.insync.replicas: 2
      transaction.state.log.replication.factor: 2
      transaction.state.log.min.isr: 1
      inter.broker.protocol.version: "3.3"
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
      - name: tlsnodeport
        port: 9094
        type: nodeport
        tls: true
        authentication:
          type: tls
      - name: routed
        authentication:
          type: tls
        tls: true
        port: 9095
        type: route
    authorization:
      type: simple
      superUsers:
        - CN=kafka-ui
    logging:
      loggers:
        log4j.logger.io.strimzi: "TRACE"
        log4j.logger.kafka: "DEBUG"
        log4j.logger.org.apache.kafka: "DEBUG"
      type: inline
    replicas: 3
    storage:
      size: 1Gi
      type: persistent-claim
  zookeeper:
    replicas: 3
    storage:
      size: 1Gi
      type: persistent-claim
