apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: trailblazers-topic
  labels:
    strimzi.io/cluster: cluster-simple-auth
  namespace: trailblazers
spec:
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
  partitions: 3
  replicas: 3
