apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: trailblazer
  labels:
    strimzi.io/cluster: cluster-simple-auth
  namespace: trailblazers
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: trailblazers-topic
          patternType: literal
        operation: Read
        host: '*'
      - resource:
          type: topic
          name: trailblazers-topic
          patternType: literal
        operation: Describe
        host: '*'
      - resource:
          type: group
          name: trailblazers-group
          patternType: literal
        operation: Read
        host: '*'
      - resource:
          type: topic
          name: trailblazers-topic
          patternType: literal
        operation: Write
        host: '*'
      - resource:
          type: topic
          name: trailblazers-topic
          patternType: literal
        operation: Describe
        host: '*'
